version: "3.8"

services:
  s3:
    container_name: s3_serivice
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "
      gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:9999"
    env_file:
      - .env
    expose:
      - 9999
    ports:
      - "9999:9999"
    networks:
      - youtube-network

  
networks:
  youtube-network:
    external: true