"""address type fix

Revision ID: 2650aae7c776
Revises: 1da9ea5847a4
Create Date: 2024-06-08 08:50:21.793480

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2650aae7c776"
down_revision = "1da9ea5847a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ip",
        "address",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ip",
        "address",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
