"""initial

Revision ID: 1da9ea5847a4
Revises: 
Create Date: 2024-06-07 18:30:26.782278

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1da9ea5847a4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ip",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("ip_pkey")),
        sa.UniqueConstraint("address", name=op.f("ip_address_key")),
    )
    op.create_index(op.f("ip_id_idx"), "ip", ["id"], unique=False)
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("tag_pkey")),
    )
    op.create_index(op.f("tag_id_idx"), "tag", ["id"], unique=False)
    op.create_index(op.f("tag_name_idx"), "tag", ["name"], unique=False)
    op.create_table(
        "video",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("video_pkey")),
    )
    op.create_index(op.f("video_id_idx"), "video", ["id"], unique=False)
    op.create_index(op.f("video_title_idx"), "video", ["title"], unique=False)
    op.create_table(
        "video_tag_association",
        sa.Column("video_id", sa.UUID(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], name=op.f("video_tag_association_tag_id_fkey")),
        sa.ForeignKeyConstraint(["video_id"], ["video.id"], name=op.f("video_tag_association_video_id_fkey")),
    )
    op.create_table(
        "video_unique_views_association",
        sa.Column("video_id", sa.UUID(), nullable=True),
        sa.Column("ip_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["ip_id"], ["ip.id"], name=op.f("video_unique_views_association_ip_id_fkey")),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.id"],
            name=op.f("video_unique_views_association_video_id_fkey"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_unique_views_association")
    op.drop_table("video_tag_association")
    op.drop_index(op.f("video_title_idx"), table_name="video")
    op.drop_index(op.f("video_id_idx"), table_name="video")
    op.drop_table("video")
    op.drop_index(op.f("tag_name_idx"), table_name="tag")
    op.drop_index(op.f("tag_id_idx"), table_name="tag")
    op.drop_table("tag")
    op.drop_index(op.f("ip_id_idx"), table_name="ip")
    op.drop_table("ip")
    # ### end Alembic commands ###
