"""user_tags

Revision ID: 2e9e6daf06c1
Revises: 2650aae7c776
Create Date: 2024-06-11 08:48:53.363529

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2e9e6daf06c1"
down_revision = "2650aae7c776"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("tag_views", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("user_tags_pkey")),
        sa.UniqueConstraint("user_id", name=op.f("user_tags_user_id_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_tags")
    # ### end Alembic commands ###
