"""url added to video

Revision ID: 5ec2aba2f0d0
Revises: 2e9e6daf06c1
Create Date: 2024-06-11 14:58:43.876959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec2aba2f0d0'
down_revision = '2e9e6daf06c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'url')
    # ### end Alembic commands ###
