version: "3.8"

services:
  users_app:
    container_name: users_app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "
      export MODE=DEV && 
      alembic upgrade head && 
      gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/src
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - youtube-network
    depends_on:
      - users_database

  users_database:
    container_name: users_base
    image: postgres:14.5
    command: postgres -c 'max_connections=1000'
    restart: always
    env_file:
      - .env
    networks:
      - youtube-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  youtube-network:
    driver: bridge

volumes:
  postgres_data:
