version: "3.8"

services:
  videos_app:
    container_name: videos_app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "
      export MODE=DEV && 
      alembic upgrade head && 
      gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/src
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - youtube-network

networks:
  youtube-network:
    external: true

